### ISSUE TITLE
살려주세요

### ISSUE THREAD

**Issue by r4pidstart** [pooh-transcendence/backend#66]
**📝 DESCRIPTION**

- Date : 2023.08.13

**☑ TODO**

[Nest] 41  - 08/13/2023, 6:00:48 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'use')
TypeError: Cannot read properties of undefined (reading 'use')
    at SocketLoggerMiddleware.use (/app/src/common/middlewares/socket-logger.middleware.ts:8:8)
    at /app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at param (/app/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/app/node_modules/express/lib/router/index.js:421:3)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at LoggerMiddleware.use (/app/src/common/middlewares/logger.middleware.ts:16:5)
[Nest] 41  - 08/13/2023, 6:00:48 AM     LOG [HTTP] ::ffff:172.19.0.1 GET 500
[Nest] 41  - 08/13/2023, 6:00:48 AM     LOG [HTTP] /user

/app/src/channel/channel.gateway.ts:75
    await this.userService.updateUserElements(user.id, {
                                                   ^
TypeError: Cannot read properties of null (reading 'id')
    at ChannelGateway.handleConnection (/app/src/channel/channel.gateway.ts:75:52)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

rest 날리는데 500 internal error 나서, 로그보니까 저렇게 떠있었고 볼륨이랑 컨테이너 다 지우고 다시 빌드했는데도 문제가 이씀

빌드하고 도커실행하고 나서 
/app/src/channel/channel.gateway.ts:75
    await this.userService.updateUserElements(user.id, {
                                                   ^
TypeError: Cannot read properties of null (reading 'id')
    at ChannelGateway.handleConnection (/app/src/channel/channel.gateway.ts:75:52)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
가 나옴

살려주어어

**Comment by ghonman2** [comment]
ChannelGateway.handleConnection 함수에 주석 처리되어있는 거 해제하고 빌드해보세용

**Comment by r4pidstart** [comment]
if (!user || user.socketId) {
      return client.disconnect();
    }
    부분 주석 해제했어요.

[Nest] 52  - 08/13/2023, 6:09:13 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'use')
TypeError: Cannot read properties of undefined (reading 'use')
    at SocketLoggerMiddleware.use (/app/src/common/middlewares/socket-logger.middleware.ts:8:8)
    at /app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at param (/app/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/app/node_modules/express/lib/router/index.js:421:3)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at LoggerMiddleware.use (/app/src/common/middlewares/logger.middleware.ts:16:5)

**Comment by yubinquitous** [comment]
지금 확인해볼게요 !

**Comment by yubinquitous** [comment]
해당 user의 id값이 null인지 한 번만 확인해주세요 !

**Comment by yubinquitous** [comment]
일단 logger 삭제해서 tjo님 살려드렸습니다-!
